#!/usr/bin/env bash
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend https
    bind *:443 ssl crt /etc/haproxy/cert.pem
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server web01 10.0.0.11:80 check
    server web02 10.0.0.12:80 check
